// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pip} from '../models';

export function GetInstalledPackages():Promise<Array<pip.Package>>;

export function GetOutdatedPackages():Promise<Array<pip.OutdatedPackage>>;

export function Greet(arg1:string):Promise<string>;

export function InstallPackage(arg1:string):Promise<void>;

export function UninstallPackage(arg1:string):Promise<void>;

export function UpgradePackage(arg1:string):Promise<void>;
